# Macro for EMMA GEANT4 simulation

# Prepare beam
#---------------------------------------------------------------
/mydet/beamZ 10
/mydet/beamA 22
/mydet/beamCharge 10
/mydet/energy 66 MeV
/mydet/sigmaEnergy 0.2         # beam-energy resolution (sigma) in percent of beam energy
/mydet/Angle 0.0 deg   	  	# beam angle sampled uniformly between 0 and theta=sigmaAngle
/mydet/beamSpotDiameter 1.0 mm
/mydet/transEmittance 0.20 mm
#---------------------------------------------------------------

# Add nuclear-reaction process: 
# (Z1,A1)+(Z2,A2)->(Z3,A3)+(Z4,A4)
#-----------------------------------------
#/twoBodyReaction/Z1 10         
#/twoBodyReaction/A1 22         
#/twoBodyReaction/Z2 3        
#/twoBodyReaction/A2 7         
#/twoBodyReaction/Z3 12         
#/twoBodyReaction/A3 26         
#/twoBodyReaction/Z4 1        
#/twoBodyReaction/A4 3         
#/twoBodyReaction/qmin 0.0   # minimum scattering angle in C.M. (deg)         
#/twoBodyReaction/qmax 180.0   # maximum ...	   
#/twoBodyReaction/Charge3 11   # charge state of fragment 3        
#-----------------------------------------



# Specify central trajectory
#----------------------------
/mydet/centralZ 12
/mydet/centralA 26
/mydet/centralQ 12
/mydet/centralE 56.3
/mydet/updategeo           # necessary for changes to take effect
#----------------------------



# Amount of output info
#-----------------------
/run/verbose      0
/event/verbose    0
/tracking/verbose 0
#-----------------------


# Run simulation
#-----------------------
/mydet/nEvents 11000     
/mydet/doPrepare
#/mydet/doBeam
#/mydet/doReaction
#-----------------------
/control/foreach ExcitationEnergyScanStep.mac ExcitationEnergy 3.588 6.256 10.159 10.573 10.824 11.183 11.336 11.500 12.345
#-----------------------------------------
